In [29]:
import torch
import torch.nn as nn

In [37]:
# Input
torch.manual_seed(42) # random state
input = torch.tensor([1.0,2.0,3.0])

In [31]:
neuron = nn.Linear(in_features=3, out_features=1)

In [32]:
output = neuron(input)

In [33]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [34]:
# Verify output 

In [35]:
print(f"Weight: {neuron.weight}\n")
print(f"Bias: {neuron.bias}")

Weight: Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

Bias: Parameter containing:
tensor([0.5304], requires_grad=True)


In [36]:
# using formula to verify

neuron.weight @ input + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)